### ISSUE TITLE
Kanban Board Project Review

### ISSUE THREAD

**Issue by t-bello7** [c3c1l1a/Micro-capstone-2#21]
- This is the link to the project - https://github.com/c3c1l1a/Micro-capstone-2/projects/3
- There are 2 participants in the team.

**Comment by Davidosky007** [comment]
Hi @t-bello7 @c3c1l1a 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has the wrong link, you should provide a link to your kanban board 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by elyor-doniyorov** [comment]
Hi @t-bello7 and @c3c1l1a, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
✅ You have sent a link to the GitHub issue that has a link to the GitHub project.
✅ Provided with the link to their GitHub project and information about the number of people in the group

## Required Changes ♻️
- [ ] Please make sure that because you are a team with **two** people - all cards with the `Student C` suffix on the template should be removed from your template.
- [ ] Also, you have not copied and added `5 group tasks` from the[ given template board](https://github.com/microverseinc/curriculum-javascript/projects/1) to your template. Kindly add them and so the overall amount of tasks will be 15. Also, do not forget to copy task title and description and assign each group task to one of you.

_Do not check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by VICTOR-CHUKWU** [comment]
Hi Team, 
# STATUS: APPROVED! 🥇 💯 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
